### ISSUE TITLE
How to rebound NMI shortcut key to right command + right option

### ISSUE THREAD

**Issue by longv2go** [klue/klue.github.io#1]
I read your blog `https://klue.github.io/blog/2017/04/macos_kernel_debugging_vbox/` , 

>Non-maskable interrupts (NMI) can be triggered by pressing control + option + command + shift + escape. Triggering an NMI will break in the debugger which is super convenient. This key combo does not play well with VirtualBox when it covers the host key combo so I rebound the host key to right command + right option.

How can I rebound the host key to right command + right option???

**Comment by klue** [comment]
VirtualBox Preferences -> Input -> Virtual Machine -> Host Key Combination
